package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f691994L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:adf25e1e-b5ca-490c-963d-5bf759864a6a(Shapes.structure)/4110518749447657876");
    b.version(3);
    b.aggregate("shapes", 0x390b7f062f691997L).target(0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f67e501L).optional(true).ordered(true).multiple(true).origin("4110518749447657879").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f691978L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f67e501L);
    b.origin("r:adf25e1e-b5ca-490c-963d-5bf759864a6a(Shapes.structure)/4110518749447657848");
    b.version(3);
    b.property("x", 0x390b7f062f691979L).type(PrimitiveTypeId.INTEGER).origin("4110518749447657849").done();
    b.property("y", 0x390b7f062f69197bL).type(PrimitiveTypeId.INTEGER).origin("4110518749447657851").done();
    b.property("radius", 0x390b7f062f69197eL).type(PrimitiveTypeId.INTEGER).origin("4110518749447657854").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f6b1ee0L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:adf25e1e-b5ca-490c-963d-5bf759864a6a(Shapes.structure)/4110518749447790304");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "ColorReference", 0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f6be792L);
    b.class_(false, false, false);
    b.origin("r:adf25e1e-b5ca-490c-963d-5bf759864a6a(Shapes.structure)/4110518749447841682");
    b.version(3);
    b.associate("target", 0x390b7f062f6be793L).target(0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f6b1ee0L).optional(false).origin("4110518749447841683").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f67e501L);
    b.class_(false, true, false);
    b.origin("r:adf25e1e-b5ca-490c-963d-5bf759864a6a(Shapes.structure)/4110518749447578881");
    b.version(3);
    b.aggregate("color", 0x390b7f062f6d2d0cL).target(0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f6be792L).optional(false).ordered(true).multiple(false).origin("4110518749447925004").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f691987L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x39c60725afc5407dL, 0xa8fe4ec957826f01L, 0x390b7f062f67e501L);
    b.origin("r:adf25e1e-b5ca-490c-963d-5bf759864a6a(Shapes.structure)/4110518749447657863");
    b.version(3);
    b.property("upperLeftX", 0x390b7f062f691988L).type(PrimitiveTypeId.INTEGER).origin("4110518749447657864").done();
    b.property("upperLeftY", 0x390b7f062f69198aL).type(PrimitiveTypeId.INTEGER).origin("4110518749447657866").done();
    b.property("size", 0x390b7f062f69198dL).type(PrimitiveTypeId.INTEGER).origin("4110518749447657869").done();
    b.alias("square");
    return b.create();
  }
}
